name: Publish Docker image
on:
  push:
    paths:
      - 'Template.Api/**'
      - 'Template.Api.IntegrationTests/**'
env:
  TagName: 0.0.1

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Print info
        run: |
          echo User $GITHUB_ACTOR triggered build on $GITHUB_REF by $GITHUB_SHA commit.
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build Template.Api
        run: dotnet build -c Release --no-cache /clp:NoSummary ./Template.Api/Template.Api.csproj
      - name: Test Template.Api
        run: dotnet test -c Release --no-build ./Template.Api/Template.Api.csproj
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repository
      - name: Check out the repo
        uses: actions/checkout@v2

      # Setting up Docker Builder
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      # Set Github Access Token with "write:packages" scope for Github Container Registry.
      # Then go to repository setings and add the copied token as a secret called "CR_PAT"
      # https://github.com/settings/tokens/new?scopes=repo,write:packages&description=Github+Container+Registry
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # Push to Github Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./Template.Api/
          file: ./Template.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.TagName }}